### ISSUE TITLE
高级会员问题

### ISSUE THREAD

**Issue by m4ra7h0n** [thebatmanfuture/fofa_search#3]
咱原来是高级会员，然后寻思不能用了就又买了个个人版。
还能变回高就会员吗。。

**Comment by thebatmanfuture** [comment]
> 咱原来是高级会员，然后寻思不能用了就又买了个个人版。
> 还能变回高就会员吗。。

啊？师傅好，我这个项目是二开的fofa_viewer，至于您说的会员问题这个得联系fofa官方捏

**Comment by ahmadShahin123** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
sssslei, @Freshield, @hoomjac, @Yeti978, @Coon-Max, @monw3c, @sunbenxin, @lanjer, @roc0723, @FlyteaR0, @herculeskan, @qq763253009, @gloryliu, @Dylan888-Xu, @JKme, @AMalikBlock, @wolong11, @liurongdong, @BolinYe, @cdoky, @linkff, @WoodyAllen2000, @cccZc, @chenxi2015, @chenchiyuan, @milerL, @BruisesL, @zycc2001, @yellowsae, @Antony-Jia, @fenghaojiang, @masonsxu, @Eisenge, @KInGATiLLa, @valenzhou, @huanglijie89, @blxdyx, @k5hello, @928907703, @blkgzs, @loganqin, @wangsihui12, @D3ic1de, @MengTL4, @AutarkXu, @Bkheep, @awangbrace, @vic-dayou, @TangHades, @pcorvoh

**Comment by manubouillon** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
xt-YUZU, @MJLNSN, @18722650553, @Jackchen-Yzu, @erwer8363, @ipodtun, @Dkbabyfzz, @glows, @falcon202110, @Hywa0510, @annecon, @badmonkey7, @brandonxiang, @Sudaxi, @d1pakda5, @Thxzzzzz, @hmpasd, @wsmmxmm, @qingfeng520, @cfengliu, @JimYan, @tunogya, @runhuayao, @HanbgCN, @langkrjianzi, @Kunsect, @ZachXia, @0xEsteban, @L2ksy0d, @kkontheway, @D3n13d, @Rowen-S, @VincentFox, @rootial, @QSlotus, @justinnzhao, @yixi-httppc, @Wzb3422, @sunzhichuang, @karthiBTC003, @wanglinyang, @youkicl, @Hinstein, @zzzmengkai123, @dacheng121, @Selipsky, @BluesVessel, @MengTL4, @Klinola, @SuperSuperFun

**Comment by manubouillon** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
0xs34n, @supr3me, @immelon0097, @ritian02, @sanjuehuo, @arielhqz, @drlappies, @shaojunda, @lianhaiming, @VilaNan, @LeeTerry92, @01001101ilad, @mmdi1, @TOBEACODER7, @HughesLiu, @0xBeshoy, @zhushaojun65, @lekclc, @echowill, @supersmartguy01, @mxmal, @it-honghui, @YuanWenHai, @jsonz1993, @zhangmin2020, @vincracker, @zxs-1024, @lackone, @fredericksfp, @ysyszheng, @DiDiDaDiDiDa, @A10ha, @ToBeWin, @rookieBC, @Qianhongrui, @youerning, @Tiancheng-Xu, @iVampireSP, @miffycs, @7IW88, @SupernovastarszjetzenoujadnZ, @yaboda-2019, @lgldppst, @zgyanglinjie, @sweetpear0108, @rickckk, @a1740942002, @menfly, @yaxuans, @ezreal1997

**Comment by manubouillon** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
caim0626, @qingjiaowopipi, @SteinNs, @Z1oftheKill, @taoeaten, @yysr008, @suddenly1990, @Acgit9666, @richardc2022, @szfdiwang, @yimings2000, @0xSY3, @Been101, @iinterest, @chenxi2015, @hui-li-yi, @zhowiny, @ykamber99, @AustinZhao0308, @jessieTanSg, @zeropool, @wang0402, @chengshihard, @ellisZk, @nooooocato, @VaughnWilber, @0xOutOfGas, @CHENkai8385, @DKnight1900, @isparkyou-github, @waxili1918, @CChCYB, @WxxW2002, @Bioboy-Learning, @Jemyun6, @suifeng00012, @Kris-hacker, @giglf, @yanglindong0725, @yang-han, @evanywhere, @yisonr, @nerr, @cwj9512-126, @0xMitchy, @JacobDu, @jkdc3kdia, @Iridescent-cdu, @Miggy0110, @Yingzhu-Liu-Star
